version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: SecretPassword12345!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - E:\DockerVolume:/var/opt/mssql/data